apiVersion: operator.zuul-ci.org/v1alpha2
kind: Zuul
metadata:
  name: zuul
spec:
  imagePrefix: docker.io/zuul
  executor:
    count: 1
    sshkey:
      secretName: executor-ssh-key
  merger:
    count: 1
  scheduler:
    config:
      secretName: zuul-yaml-conf
  launcher:
    config:
      secretName: nodepool-yaml-conf
  connections:
    opendev:
      driver: git
      baseurl: https://opendev.org
  externalConfig:
    kubernetes:
      secretName: nodepool-kube-config
#  database:
#    allowUnsafeConfig: true
